DROP TABLE IF EXISTS "ASNs";

CREATE TABLE "ASNs"
(
    "id"     INTEGER PRIMARY KEY AUTOINCREMENT,
    "number" TEXT NOT NULL,
    "name"   TEXT NOT NULL
);

CREATE UNIQUE INDEX "asn_key" ON "ASNs" ("number");