name = "asn-cn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-10-10"

routes = [
    { pattern = "asn-cn.oio.sd", custom_domain = true }
]
workers_dev = false

[triggers]
crons = ["0 0 * * *"]

[build]
command = "pnpm run build && cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "asn-cn"
database_id = "bf5a766d-9745-46d5-8c65-1be093efd2c4"

[[kv_namespaces]]
binding = "kv"
id = "cae722bec8644af4a3b6f7f9333b646e"

[observability]
enabled = true

[assets]
directory = "./assets/out"
