name = "asn-cn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-10-10"

routes = [
    { pattern = "asn-cn.oio.sd", custom_domain = true }
]
workers_dev = false

[triggers]
crons = ["0 0 * * *"]

[build]
command = "pnpm run build && cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "asn-cn"
database_id = "3652d109-2609-4a27-b7c5-b176e51e47b1"

[observability]
enabled = true

[assets]
directory = "./assets/out"
