[package]
name = "crawler"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Homing So <i@homing.so>"]

[lib]
name = "crawler"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.0"
reqwest = "0.12.8"
entity = { path = "../entity" }
