on: [ push, pull_request ]

name: CI

env:
  RUSTTOOLCHAIN: "stable"

jobs:
  deeplx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check --all-targets

      - name: Run cargo test
        run: cargo test --all-targets

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings